### ISSUE TITLE
[BUG]: ops.conv2d produces incorrect results when C_in >= 8 (groups=1, RSCF layout)

### ISSUE THREAD

**Issue by itsdevcoffee** [modular/modular#6248]
## Environment

* MAX version: 26.3.0.dev2026032005
* Platform: linux-64 (x86_64)
* GPU: NVIDIA GeForce RTX 4060 Ti, CUDA 13.0
* Pixi version: 0.61.0

## Description

`ops.conv2d` returns incorrect results when the number of input channels (C_in) is >= 8, even with `groups=1` (standard convolution). The output diverges from both PyTorch and a manual numpy ground-truth computation. C_in <= 6 produces exact results.

The error grows with C_in and is independent of kernel size:

```
C_in=  2, C_out=  4, K=3: max_diff=0.00000000  [PASS]
C_in=  4, C_out=  8, K=3: max_diff=0.00000000  [PASS]
C_in=  6, C_out= 12, K=3: max_diff=0.00000000  [PASS]
C_in=  8, C_out= 16, K=3: max_diff=0.01723001  [FAIL]
C_in= 16, C_out= 32, K=3: max_diff=0.02368748  [FAIL]
C_in= 32, C_out= 64, K=3: max_diff=0.03833004  [FAIL]
C_in= 64, C_out=128, K=3: max_diff=0.09013467  [FAIL]
C_in=192, C_out=384, K=3: max_diff=0.11577050  [FAIL]
C_in=192, C_out=512, K=7: max_diff=0.16524951  [FAIL]
```

This blocks the NSF-HiFiGAN vocoder (all Conv1d layers have C_in >= 32) from producing numerically correct output in our mojo-audio voice conversion pipeline.

**Possible root cause:** The C_in=8 threshold suggests a filter packing issue tied to the SIMD/micro-kernel tile width (AVX2: 8 floats). The packing may read past the filter boundary or misalign channels when `C_in >= micro_tile_width`, similar to the `pack_filter` bug fixed in [KERN-2567](https://linear.app/modularml/issue/KERN-2567/bug-opsconv2d-produces-incorrect-results-with-groups-1-and-large) for the `groups > 1` case.

## Repro script

The script compares MAX `ops.conv2d` output against a manual numpy convolution loop (ground truth). It also verifies PyTorch matches numpy exactly (confirming the reference is correct).

```python
"""Repro: ops.conv2d incorrect results when C_in >= 8."""
import numpy as np
from max import engine
from max.graph import Graph, TensorType, ops, DeviceRef, Dim
from max.dtype import DType
from max.driver import CPU

def numpy_conv2d(x_nhwc, w_rscf, pad_h):
    """Ground-truth Conv2d via numpy loops."""
    B, H, W, C_in = x_nhwc.shape
    R, S, C_in_f, C_out = w_rscf.shape
    x_pad = np.pad(x_nhwc, ((0,0), (pad_h, pad_h), (0,0), (0,0)))
    out = np.zeros((B, H, 1, C_out), dtype=np.float32)
    for b in range(B):
        for t in range(H):
            for co in range(C_out):
                val = 0.0
                for ci in range(C_in):
                    for r in range(R):
                        val += w_rscf[r, 0, ci, co] * x_pad[b, t + r, 0, ci]
                out[b, t, 0, co] = val
    return out

def max_conv2d(x_nhwc, w_rscf, pad_h):
    """Same conv via MAX Graph."""
    B, H, W, C_in = x_nhwc.shape
    R, S, C_in_f, C_out = w_rscf.shape
    cpu_ref = DeviceRef.CPU()
    with Graph("t", input_types=[TensorType(DType.float32, [B, Dim("T"), 1, C_in], cpu_ref)]) as g:
        inp = g.inputs[0]
        padded = ops.pad(inp, [0, 0, pad_h, pad_h, 0, 0, 0, 0])
        out = ops.conv2d(padded, ops.constant(w_rscf, device=cpu_ref), stride=(1, 1))
        g.output(out)
    model = engine.InferenceSession(devices=[CPU()]).load(g)
    result = model.execute(np.ascontiguousarray(x_nhwc))
    tensor = list(result.values())[0] if isinstance(result, dict) else result[0]
    return tensor.to_numpy()

# Test: C_in=8 fails, C_in=4 passes
for C_in in [4, 8, 64, 192]:
    rng = np.random.default_rng(42)
    C_out, K, T = C_in * 2, 3, 5
    w_pt = rng.standard_normal((C_out, C_in, K)).astype(np.float32) * 0.01
    w_rscf = np.transpose(w_pt, (2, 1, 0))[:, np.newaxis, :, :]
    x = rng.standard_normal((1, T, 1, C_in)).astype(np.float32) * 0.1
    pad = (K - 1) // 2
    np_out = numpy_conv2d(x, w_rscf, pad)
    max_out = max_conv2d(x, w_rscf, pad)
    diff = np.abs(np_out - max_out).max()
    print(f"C_in={C_in:>3}: max_diff={diff:.8f}  {'PASS' if diff < 1e-5 else 'FAIL'}")
```

### Steps to reproduce

1. Install MAX 26.3.0 nightly
2. Run the script above
3. Observe: C_in=4 passes, C_in >= 8 fails with growing error

### System information

```
Platform: linux-64 (x86_64)
Pixi version: 0.61.0
MAX: 26.3.0.dev2026032005
```

### Workaround

We are implementing Conv1d via im2col + matmul as a workaround until this is fixed.

### Related

This may share a root cause with [KERN-2567](https://linear.app/modularml/issue/KERN-2567/bug-opsconv2d-produces-incorrect-results-with-groups-1-and-large) (filter packing bug for groups > 1), which was fixed in the same MAX version. The groups=1 case may have a similar packing issue for `C_in >= micro_kernel_c_size`.

**Comment by itsdevcoffee** [comment]
Hey team — wanted to share an update on this since we've been building around it for the past few weeks.

We're implementing a full RVC v2 voice conversion pipeline in MAX Engine ([mojo-audio](https://github.com/itsdevcoffee/mojo-audio)) and this bug blocks every Conv1d layer in the network (all have C_in >= 32). We ended up replacing **all** `ops.conv2d` usage with an im2col + matmul workaround:

1. Pad input along T for "same" output
2. Extract K shifted slices via `ops.slice_tensor`
3. Concat along channel dim → `[B, T, K*C_in]`
4. Matmul with reshaped weight `[K*C_in, C_out]`

This pattern works for standard conv1d, dilated conv, strided conv (downsampling), and even ConvTranspose1d (zero-interleave + im2col). With it, our HiFiGAN vocoder matches PyTorch at **0.9998 correlation**, confirming the underlying MAX infrastructure (matmul, symbolic shapes, graph compilation) is solid — it's specifically `ops.conv2d` that produces wrong values for C_in >= 8.

We also hit a related issue: **multiple `ops.conv2d` calls with different stride configurations in the same graph** cause a compiler crash during `session.load()`:

```
ValueError: Graph compilation failed:
error: All operation types must have the same shape
```

Individual conv2d ops compile fine in isolation — the error only appears when the graph contains 2+ conv2d ops with different strides/paddings. The im2col workaround avoids this too.

Happy to provide a minimal repro for the multi-stride compiler crash if that's useful. The im2col workaround code is in our repo at `src/models/_hifigan_graph.py` if anyone else needs it.

**Comment by itsdevcoffee** [comment]
Hey team — retested `26.3.0.dev2026041020` (April 10 nightly) across both platforms. **CPU-only** testing on both aarch64 and x64. Interesting split: the multi-stride compiler crash is fixed everywhere, but the main C_in ≥ 8 numerical bug is only fixed on aarch64. x64 is still broken with nearly-identical error values to the original report.

## `ops.conv2d` C_in ≥ 8 numerical bug

**linux-aarch64 CPU (NVIDIA DGX Spark, GB10):** ✅ PASSES
```
C_in=  2, C_out=  4, K=3: max_diff=0.00000000  [PASS]
C_in=  4, C_out=  8, K=3: max_diff=0.00000000  [PASS]
C_in=  6, C_out= 12, K=3: max_diff=0.00000000  [PASS]
C_in=  8, C_out= 16, K=3: max_diff=0.00000000  [PASS]
C_in= 16, C_out= 32, K=3: max_diff=0.00000000  [PASS]
C_in= 32, C_out= 64, K=3: max_diff=0.00000001  [PASS]
C_in= 64, C_out=128, K=3: max_diff=0.00000002  [PASS]
C_in=192, C_out=384, K=3: max_diff=0.00000009  [PASS]
C_in=192, C_out=512, K=7: max_diff=0.00000013  [PASS]
```
Everything matches numpy ground truth within float32 precision. K=7/C_in=192 worst case went from `0.165` to `1.3e-7`.

**linux-x64 CPU (Fedora 43, RTX 4060 Ti box):** ❌ STILL BROKEN
```
C_in=  2, C_out=  4, K=3: max_diff=0.00000000  [PASS]
C_in=  4, C_out=  8, K=3: max_diff=0.00000000  [PASS]
C_in=  6, C_out= 12, K=3: max_diff=0.00000000  [PASS]
C_in=  8, C_out= 16, K=3: max_diff=0.01723001  [FAIL]
C_in= 16, C_out= 32, K=3: max_diff=0.02368748  [FAIL]
C_in= 32, C_out= 64, K=3: max_diff=0.03833004  [FAIL]
C_in= 64, C_out=128, K=3: max_diff=0.09013467  [FAIL]
C_in=192, C_out=384, K=3: max_diff=0.11577050  [FAIL]
C_in=192, C_out=512, K=7: max_diff=0.19144066  [FAIL]
```

K=3 values are **byte-identical** to the original March 2026 report. **K=7/C_in=192 moved** from `0.165` to `0.191` despite the numpy seed being identical (`np.random.default_rng(42)`) — so something in the x64 backend did change, but in the wrong direction for this case. Error still grows monotonically with C_in:

| C_in | K=3 max_diff | vs C_in=8 |
|------|-------------|-----------|
| 8 | 0.0172 | 1.00× |
| 16 | 0.0237 | 1.37× |
| 32 | 0.0383 | 2.22× |
| 64 | 0.0901 | 5.24× |
| 192 | 0.1158 | 6.73× |

The C_in=8 threshold still matches the original AVX2 8-float micro-tile packing theory on x64. Whatever landed for aarch64 may well be a separate kernel path rather than a fix to the underlying x64 packing issue — worth cross-checking with whoever owns the backend.

## Multi-stride compiler crash (mentioned in my earlier follow-up)

✅ **Fixed on both platforms.** Previously, a graph containing 2+ `ops.conv2d` ops with different stride or padding configurations would fail at `session.load()` with:
```
ValueError: Graph compilation failed:
error: All operation types must have the same shape
```

Now compiles and runs cleanly on both aarch64 and x64. Tested with:
- Two conv2d ops, `stride=(1,1)` then `stride=(2,1)` → compiles + runs
- Two conv2d ops, `padding=(1,1,1,1)` then `padding=(0,0,0,0)` → compiles + runs

## Caveats

- **CPU only.** Both repros use `DeviceRef.CPU()` / `CPU()` driver. We haven't retested under `Accelerator()` on either platform, so the GPU paths may differ from the CPU numbers above. Original issue mentioned the 4060 Ti as the platform but attached a CPU-only repro, so the GPU status of this bug has always been unclear.
- **aarch64 fix is point-level correctness only.** Individual `ops.conv2d` calls now match ground truth within float32 precision on aarch64, but we haven't yet validated whether cumulative rounding through a deep conv stack (our HiFiGAN has ~70 stacked convs) has changed relative to our im2col workaround. That's the next thing for us to measure before deciding whether to pull the workaround out of the vocoder.

## Status

- **aarch64**: can start migrating off the im2col workaround — pending cumulative-drift validation on our full HiFiGAN / RMVPE U-Net
- **x64**: still needs the im2col workaround, still blocks correctness on x64 deployments
- Issue should stay open until x64 is fixed

Happy to share the conv2d and multi-stride repro scripts if helpful.
